export const cartActionsTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEMS_CART: 'ADD_ITEMS_CART',
    REMOVE_ITEM_FROM_BASKET: 'REMOVE_ITEM_FROM_BASKET',
    REMOVE_ONE_ITEM_FROM_CARD: 'REMOVE_ONE_ITEM_FROM_CARD',
    ADD_ONE_ITEM_FROM_CARD: 'ADD_ONE_ITEM_FROM_CARD',
    CLEAR_OUT_BASKET: 'CLEAR_OUT_BASKET'
}