const userActionsTypes = {
    GOOGLE_SIGN_IN_START:'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START:'EMAIL_SIGN_IN_START',
    EMAIL_SIGN_UP_START: 'EMAIL_SIGN_UP_START',
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE:'SIGN_IN_FAILURE',
    EMAIL_SIGN_UP_SUCCESS: 'EMAIL_SIGN_UP_SUCCESS',
    EMAIL_SIGN_UP_FAILURE: 'EMAIL_SIGN_UP_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    USER_SIGNED_OUT_START: 'USER_SIGNED_OUT_START',
    USER_SIGNED_OUT_SUCCESS: 'USER_SIGNED_OUT_SUCCESS',
    USER_SIGNED_OUT_FAILURE: 'USER_SIGNED_OUT_FAILURE'
}

export default userActionsTypes;